version: '2.1'
services:
  inno-team-front:
    container_name: inno_team_front
    build: frontend
    environment:
      VUE_APP_BACKEND_URL: http://inno-team-back:9090
      VUE_APP_KEYCLOAK_URL: http://localhost:9000/auth
    ports:
      - "8080:8080"
    depends_on:
      inno-team-back:
        condition: service_started
  inno-team-back:
    container_name: inno_team_back
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      KEYCLOAK_AUTHSERVERURL: http://keycloak:9000/auth
    ports:
      - "9090:9090"
    depends_on:
      elasticsearch:
        condition: service_healthy
      keycloak:
        condition: service_started

  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: keycloak
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin1234
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_FRONTEND_URL: http://localhost:9000/auth
    ports:
      - "9000:9000"
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    command:
      - -Djboss.http.port=9000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/auth/" ]
      interval: 5s
      timeout: 2s
      retries: 15
    depends_on:
      - db
  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      retries: 2
volumes:
  esdata:
  pgdata:
