version: '2.1'
services:
  inno-team-front:
    container_name: inno_team_front
    build: frontend
    environment:
      VUE_APP_BACKEND_URL: http://inno-team:9090
    ports:
      - "8080:8080"
    depends_on:
      inno-team:
        condition: service_started
  inno-team:
    container_name: inno_team
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    ports:
      - "9090:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      retries: 2
volumes:
  esdata: